management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  endpoint:
    health:
#      show-details: always
      show-components: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/manage"
  server:
    port: 9292

info:
    app:
      name: hello-actuator
      company: yh
server:
  port: 8081

logging:
  level:
    hello.controller: debug
